In [1]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head(5)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
df = df.iloc[:,2:]

In [4]:
df.head()

Review eductaion purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# train test

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

# Odenal encoding

In [6]:
x_train

Review eductaion
23     Good    School
12     Poor    School
40     Good    School
44  Average        UG
18     Good    School
3      Good        PG
4   Average        UG
2      Good        PG
28     Poor    School
21  Average        PG
24  Average        PG
41     Good        PG
48     Good        UG
16     Poor        UG
1      Poor        UG
42     Good        PG
29  Average        UG
37  Average        PG
34  Average    School
47     Good        PG
5   Average    School
9      Good        UG
26     Poor        PG
32  Average        UG
19     Poor        PG
43     Poor        PG
7      Poor    School
46     Poor        PG
33     Good        PG
15     Poor        UG
11     Good        UG
0   Average    School
14     Poor        PG
30  Average        UG
22     Poor        PG
20  Average    School
8   Average        UG
10     Good        UG
38     Good    School
13  Average    School

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [9]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [10]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [11]:
x_train

array([[2., 0.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [1., 0.]])

In [12]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# lebal encoder

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

In [15]:
le.fit(y_train)

LabelEncoder()

In [16]:
le.classes_


array(['No', 'Yes'], dtype=object)

In [17]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [18]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0])

In [19]:
y_test

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# feacher scaling

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
sc =  StandardScaler()

In [25]:
x_train = sc.fit_transform(x_train)

In [26]:
x_test = sc.fit_transform(x_test)

In [27]:
x_train

array([[ 1.18060256, -1.31393451],
       [-1.30487651, -1.31393451],
       [ 1.18060256, -1.31393451],
       [-0.06213698, -0.09166985],
       [ 1.18060256, -1.31393451],
       [ 1.18060256,  1.13059481],
       [-0.06213698, -0.09166985],
       [ 1.18060256,  1.13059481],
       [-1.30487651, -1.31393451],
       [-0.06213698,  1.13059481],
       [-0.06213698,  1.13059481],
       [ 1.18060256,  1.13059481],
       [ 1.18060256, -0.09166985],
       [-1.30487651, -0.09166985],
       [-1.30487651, -0.09166985],
       [ 1.18060256,  1.13059481],
       [-0.06213698, -0.09166985],
       [-0.06213698,  1.13059481],
       [-0.06213698, -1.31393451],
       [ 1.18060256,  1.13059481],
       [-0.06213698, -1.31393451],
       [ 1.18060256, -0.09166985],
       [-1.30487651,  1.13059481],
       [-0.06213698, -0.09166985],
       [-1.30487651,  1.13059481],
       [-1.30487651,  1.13059481],
       [-1.30487651, -1.31393451],
       [-1.30487651,  1.13059481],
       [ 1.18060256,

In [28]:
x_test

array([[ 1.22474487,  0.12038585],
       [ 1.22474487,  0.12038585],
       [-0.81649658,  1.32424438],
       [-0.81649658,  1.32424438],
       [-0.81649658,  1.32424438],
       [-0.81649658, -1.08347268],
       [ 1.22474487, -1.08347268],
       [-0.81649658,  0.12038585],
       [ 1.22474487, -1.08347268],
       [-0.81649658, -1.08347268]])